language: cpp

sudo: required

services:
  - docker

before_install:
- docker pull insighttoolkit/simpleitk-notebooks:2015-miccai

script:
- cd ~/SimpleITKTutorialSPIE2016 && python ./downloaddata.py ./Data ./Data/manifest.json
- docker run -v ~/SimpleITKTutorialSPIE2016:/home/jovyan/notebooks insighttoolkit/simpleitk-notebooks:2015-miccai ./test.sh

