sudo: required

services:
  - docker

before_install:
- docker pull insighttoolkit/simpleitk-notebooks:2015-miccai

script:
- python ./downloaddata.py ./Data ./Data/manifest.json
- docker run -v $PWD:/home/jovyan/notebooks insighttoolkit/simpleitk-notebooks:2015-miccai ./test.sh

